Repository moodCatcherProject/Front-End, pull requests merged in 2022-09, with the labels that each got.

#16 #15 edit.전체적인 css완성 및 함수추가
  db.json
  public/images/heart.png
  src/App.js
  src/components/loginComponents/LoginForm.jsx
  src/components/signupComponents/SignupGenderAge.jsx
  src/elem/Header.jsx
  src/elem/NavigationBar.jsx
  src/page/Login.jsx
  src/page/Main.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
  src/redux/modules/loginSlice.jsx
  src/redux/modules/uploadSlice.jsx
  src/shared/Loader.js
  src/shared/style/TestHeader.css
Labels: update

#25 Feature/closet
  package.json
  public/images/upArrow.png
  src/App.js
  src/components/closetComponents/ClosetPosts.jsx
  src/components/closetComponents/EachPost.jsx
  src/components/closetComponents/InfinityScrollLoader.jsx
  src/components/detailComponents/DetailChangeComments.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/likeComponents/EachPost.jsx
  src/components/likeComponents/InfinityScrollLoader.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/loginComponents/LoginForm.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/mainComponents/InfinityScrollLoader.jsx
  src/components/mainComponents/RepPost.jsx
  src/components/mypageComponents/ClosetForm.jsx
  src/components/mypageComponents/GradeList.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/searchComponents/SearchFrom.jsx
  src/components/searchComponents/SearchResultForm.jsx
  src/components/signupComponents/SignupForm.jsx
  src/components/signupComponents/SignupGenderAge.jsx
  src/elem/Header.jsx
  src/elem/NavigationBar.jsx
  src/page/Closet.jsx
  src/page/Item_detail.jsx
  src/page/Like.jsx
  src/page/Main.jsx
  src/page/Mypage.jsx
  src/page/Search.jsx
  src/page/Upload_select.jsx
  src/redux/configStore.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/loginSlice.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/signUpSlice.jsx
  src/redux/modules/uploadSlice.jsx
  src/shared/style/scrollLoader.css
Labels: enhancement

#30 update/main
  src/components/loginComponents/LoginForm.jsx
  src/components/profileComponents/EditProfileForm.jsx
  src/components/signupComponents/SignupForm.jsx
  src/components/signupComponents/SignupGenderAge.jsx
  src/redux/modules/loginSlice.jsx
  src/shared/api.js
Labels: bug

#33 Update/upload
  package.json
  src/components/likeComponents/EachPost.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/uploadCompnents/EachMusinsa.jsx
  src/elem/NavigationBar.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/page/Mypage.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
  src/redux/modules/loginSlice.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/uploadSlice.jsx
  yarn.lock
Labels: enhancement, update

#40 Update/item detail
  src/App.js
  src/components/closetComponents/InfinityScrollLoader.jsx
  src/components/detailComponents/DetailChangeComments.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/likeComponents/EachPost.jsx
  src/components/likeComponents/InfinityScrollLoader.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/InfinityScrollLoader.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/uploadSlice.jsx
Labels: update

#52 #51 update.totop기능 구현
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/mainComponents/EachPost.jsx
  src/page/Like.jsx
  src/page/Main.jsx
  src/redux/configStore.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/likeSlice.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/uploadSlice.jsx
Labels: update

#61 #60 bugfix.가로스크롤 pc도 가능하게, 대댓글 수정,삭제
  src/components/detailComponents/DetailChangeReComments.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/profileCompnents/EditProfileForm.jsx
  src/elem/NavigationBar.jsx
  src/page/Edit_post_select.jsx
  src/page/Edit_profile.jsx
  src/page/Item_detail.jsx
  src/page/Search.jsx
  src/page/Signup.jsx
  src/page/Upload_select.jsx
  src/redux/modules/commentSlice.jsx
Labels: update

#65 #57 bugfix.대표게시물, 댓글, 무한스크롤 버그픽스
  public/images/noimage.PNG
  src/components/alarmComponents/AlarmForm.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/mainComponents/RepPost.jsx
  src/components/searchComponents/SearchResultForm.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/signUpSlice.jsx
Labels: bug

#72 #67 Develop
  src/components/detailComponents/DetailCommentList.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/uploadCompnents/EachMusinsa.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/uploadSlice.jsx
Labels: bug, update

#74 Develop
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/profileComponents/EditProfileForm.jsx
  src/components/searchComponents/SearchFrom.jsx
  src/components/searchComponents/SearchResultForm.jsx
  src/components/uploadCompnents/EachMusinsa.jsx
  src/elem/Header.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/page/Mypage.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/uploadSlice.jsx
Labels: bug, enhancement, update

#75 develop
  src/components/closetComponents/EachPost.jsx
  src/components/detailComponents/DetailChangeComments.jsx
  src/components/detailComponents/DetailChangeReComments.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/likeComponents/EachPost.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/mainComponents/RepPost.jsx
  src/components/searchComponents/SearchFrom.jsx
  src/elem/NavigationBar.jsx
  src/page/Item_detail.jsx
  src/redux/modules/likeSlice.jsx
  src/redux/modules/rankSlice.jsx
Labels: bug

#79 Bugfix/main
  README.md
  public/images/arrow_back.png
  src/components/detailComponents/DetailChangeComments.jsx
  src/components/detailComponents/DetailChangeReComments.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/RepPost.jsx
  src/elem/Header.jsx
  src/elem/NavigationBar.jsx
  src/page/Closet.jsx
  src/page/Edit_post.jsx
  src/page/Edit_post_select.jsx
  src/page/Item_detail.jsx
  src/page/Like.jsx
  src/page/Main.jsx
  src/page/Search.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
Labels: bug, update

#83 Merge/develop
  README.md
  src/components/alarmComponents/AlarmForm.jsx
  src/elem/NavigationBar.jsx
  src/page/Item_detail.jsx
Labels: documentation

#87 #67 Update/token
  package.json
  src/App.js
  src/components/alarmComponents/AlarmForm.jsx
  src/components/closetComponents/ClosetPosts.jsx
  src/components/closetComponents/EachPost.jsx
  src/components/detailComponents/DetailChangeComments.jsx
  src/components/detailComponents/DetailChangeReComments.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/likeComponents/EachPost.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/loginComponents/LoginForm.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/mainComponents/RepPost.jsx
  src/components/mypageComponents/GradeList.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/openComponents/OpenForm.jsx
  src/components/profileComponents/EditProfileForm.jsx
  src/components/searchComponents/SearchFrom.jsx
  src/components/searchComponents/SearchItem.jsx
  src/components/searchComponents/SearchResultForm.jsx
  src/components/signupComponents/SignupForm.jsx
  src/components/signupComponents/SignupGenderAge.jsx
  src/elem/Buttons.jsx
  src/elem/GlobalStyle.jsx
  src/elem/Header.jsx
  src/elem/Input.jsx
  src/elem/NavigationBar.jsx
  src/elem/ScrollX.jsx
  src/page/Edit_post_select.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/page/Search.jsx
  src/page/Signup.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
  src/redux/async/alarm.jsx
  src/redux/async/comment.jsx
  src/redux/async/like.jsx
  src/redux/async/login.jsx
  src/redux/async/rank.jsx
  src/redux/async/search.jsx
  src/redux/async/signup.jsx
  src/redux/async/upload.jsx
  src/redux/modules/alarmSlice.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/likeSlice.jsx
  src/redux/modules/loginSlice.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/searchSlice.jsx
  src/redux/modules/signUpSlice.jsx
  src/redux/modules/uploadSlice.jsx
  src/shared/api.js
  src/shared/cookie.js
  yarn.lock
Labels: documentation, update

#89 #86 update.pwa 및 무한스크롤 last페이지
  package.json
  public/favicon1.ico
  public/favicon2.ico
  public/image/katalk_default.jpg
  public/images/moodcatcher.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/moodcatcher150.png
  public/moodcatcher512.png
  public/offline.html
  public/serviceworker.js
  src/components/closetComponents/ClosetPosts.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/searchComponents/SearchFrom.jsx
  src/components/searchComponents/SearchResultForm.jsx
  src/elem/Button.jsx
  src/elem/PwaButton.jsx
  src/index.js
  src/page/Main.jsx
  src/redux/async/like.jsx
  src/redux/async/rank.jsx
  src/redux/async/search.jsx
  src/redux/async/upload.jsx
  src/redux/modules/likeSlice.jsx
  src/redux/modules/searchSlice.jsx
  src/redux/modules/uploadSlice.jsx
  src/reportWebVitals.js
  src/shared/api.js
  yarn.lock
Labels: documentation, enhancement, update

#95 #94 update.코드스플리팅 loadable로 변경
  package.json
  src/App.js
  src/components/loginComponents/LoginForm.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/searchComponents/SearchFrom.jsx
  src/page/Alarm.jsx
  src/page/Closet.jsx
  src/page/Edit_password.jsx
  src/page/Edit_post.jsx
  src/page/Edit_post_select.jsx
  src/page/Edit_profile.jsx
  src/page/GenderAge.jsx
  src/page/Item_detail.jsx
  src/page/Like.jsx
  src/page/Login.jsx
  src/page/Main.jsx
  src/page/Mypage.jsx
  src/page/Open.jsx
  src/page/Search.jsx
  src/page/Search_result.jsx
  src/page/Signup.jsx
  src/page/Upload.jsx
  src/page/Upload_select.jsx
  src/shared/Loader.js
  yarn.lock
Labels: update

#117 #116 feature.카카오맵 구현 및 잔에러 수정
  public/images/Map.png
  public/index.html
  src/App.js
  src/components/searchComponents/SearchFrom.jsx
  src/elem/Header.jsx
  src/page/MapImage.jsx
  src/page/MapImageStyle.css
  src/redux/async/kakao.jsx
  src/redux/async/upload.jsx
  src/redux/configStore.jsx
  src/redux/modules/kakaoSlice.jsx
  src/shared/api.js
Labels: enhancement, update

#118 #67 add.명예의 전당페이지 완성
  src/App.js
  src/components/alarmComponents/AlarmForm.jsx
  src/components/bestPostsComponents/BestPostsForm.jsx
  src/components/likeComponents/EachPost.jsx
  src/components/loginComponents/LoginForm.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/mypageComponents/GradeList.jsx
  src/components/mypageComponents/MyPageForm.jsx
  src/components/openComponents/OpenForm.jsx
  src/components/searchComponents/SearchItem.jsx
  src/components/searchComponents/SearchResultForm.jsx
  src/components/signupComponents/EditPasswordForm.jsx
  src/components/signupComponents/SignupForm.jsx
  src/components/signupComponents/SignupGenderAge.jsx
  src/elem/Header.jsx
  src/image/heart.png
  src/image/heartTrue.png
  src/page/Edit_password.jsx
  src/page/GenderAge.jsx
  src/page/Item_detail.jsx
  src/redux/async/signup.jsx
  src/redux/modules/rankSlice.jsx
  src/redux/modules/searchSlice.jsx
  src/redux/modules/signUpSlice.jsx
  src/shared/api.js
Labels: update

#122 #121 feature.구글 애널리틱스 및 og카드
  public/index.html
Labels: enhancement, update

#128 Update/main
  public/images/chat.png
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/openComponents/OpenForm.jsx
  src/page/Item_detail.jsx
  src/page/MapImage.jsx
  src/page/Open.jsx
  src/redux/modules/kakaoSlice.jsx
Labels: bug, update

#132 # 131 Update/main
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/loginComponents/LoginForm.jsx
  src/components/mainComponents/AllPosts.jsx
  src/components/mainComponents/EachPost.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/uploadCompnents/EachMusinsa.jsx
  src/elem/Button.jsx
  src/elem/Header.jsx
  src/elem/InfinityScrollLoader.jsx
  src/page/Edit_post_select.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/page/Upload_select.jsx
  src/redux/modules/uploadSlice.jsx
  src/shared/api.js
Labels: update

#135 hotfix.test전 error잠시 주석처리
  src/redux/async/comment.jsx
Labels: update

#137 Update/main
  public/images/upArrow.png
  src/components/alarmComponents/AlarmForm.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/components/detailComponents/DetailRecomments.jsx
  src/components/likeComponents/EachPost.jsx
  src/components/likeComponents/LikePosts.jsx
  src/components/mainComponents/HotPosts.jsx
  src/components/signupComponents/SignupForm.jsx
  src/components/signupComponents/SignupGenderAge.jsx
  src/components/uploadCompnents/EachMusinsa.jsx
  src/index.js
  src/page/Edit_post_select.jsx
  src/page/Item_detail.jsx
  src/page/MapImage.jsx
  src/page/Upload_select.jsx
  src/redux/async/comment.jsx
  src/redux/async/kakao.jsx
  src/redux/async/rank.jsx
  src/redux/async/signup.jsx
  src/redux/async/upload.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/kakaoSlice.jsx
  src/shared/api.js
Labels: update

#142 Update/main
  src/App.js
  src/components/alarmComponents/AlarmForm.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/mainComponents/HotPosts.jsx
  src/elem/Header.jsx
  src/page/Item_detail.jsx
  src/page/Main.jsx
  src/shared/api.js
  src/shared/style/MapImageStyle.css
Labels: bug, update

#152 bugfix.댓글 대댓글 복제관련 버그픽스
  src/components/detailComponents/DetailChangeComments.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/page/Item_detail.jsx
  src/redux/modules/commentSlice.jsx
Labels: bug

#154 #141 bugfix.댓글무한스크롤제거,핫포스트,모바일규격,로그아웃정상화
  src/components/mainComponents/HotPosts.jsx
  src/components/profileComponents/EditProfileForm.jsx
  src/page/Item_detail.jsx
  src/redux/async/comment.jsx
  src/redux/async/login.jsx
  src/redux/modules/commentSlice.jsx
  src/redux/modules/loginSlice.jsx
  src/shared/api.js
Labels: bug

#171 Update/main
  src/components/alarmComponents/AlarmForm.jsx
  src/components/detailComponents/DetailCommentList.jsx
  src/components/detailComponents/DetailReCommentList.jsx
  src/page/Item_detail.jsx
Labels: bug
